version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  rpc_user_service:
    build: .
    command: python user_service.py
    ports:
      - "8000:8000"

  api1:
    build: .
    command: python app.py
    depends_on:
      - rabbitmq
      - rpc_user_service
    volumes:
      - shared_db:/app/instance  # <-- Pintu rahasia untuk API 1

  api2:
    build: .
    command: python app.py
    depends_on:
      - rabbitmq
      - rpc_user_service
    volumes:
      - shared_db:/app/instance  # <-- Pintu rahasia untuk API 2

  worker:
    build: .
    command: python worker.py
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2
    volumes:
      - shared_db:/app/instance  # <-- Pintu rahasia untuk Pekerja

  nginx_lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - api1
      - api2 

volumes:
  shared_db: